### ISSUE TITLE
CMD throwing errors trying to run

### ISSUE THREAD

**Issue by Bradw-17** [davidfischer/mtg-printable-set-label-generator#6]
I'm not any kind of programmer, but I do understand some basics principles and think I followed the instructions correctly. However, I'm no good at debugging and I keep getting the following error when trying to run the program:

`C:\Users\-----\Downloads\mtg-label-gen>python label-generator.py
Traceback (most recent call last):
  File "C:\Users\-----\Downloads\mtg-label-gen\label-generator.py", line 7, in <module>
    import cairosvg
  File "C:\Python39\lib\site-packages\cairosvg\__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Python39\lib\site-packages\cairosvg\surface.py", line 9, in <module>
    import cairocffi as cairo
  File "C:\Python39\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Python39\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e`

**Comment by davidfischer** [comment]
You have some sort of linker error with Cairo (the library that converts SVGs to PDFs). I don't know why it failed to install correctly.

**Comment by floppflopp1** [comment]
I am getting the exact same error, and I have also done my best to follow the instructions. The issue is surely Cairo as I have been struggling with this error for the past 4 hours. Pip, local installation, paths - same error and no progress. I will make another attempt in a couple of days as your work appears to be stellar, and I would love to use it for cataloging the collection.

**Comment by davidfischer** [comment]
I'm going to generate a web frontend that will let people generate these labels themselves without having to install it.

It might take a few days as my time is pretty limited.

**Comment by davidfischer** [comment]
I have a first cut of the web frontend here: https://mtg-label-generator.herokuapp.com/

There's still some more work to do:

- It's not using the custom fonts which are more similar to MTG's own fonts
- Handle a bunch more shortened names which won't fit otherwise
- Some presets for selecting groups of sets (although I suspect the default is what almost everybody wants)

**Comment by floppflopp1** [comment]
Excellent work! Thank you very much for creating a web frontend in such a short time - it really made my weekend!

**Comment by davidfischer** [comment]
Alright. I fixed the issues with the custom fonts (they're displaying now) and added a few quick select groups. There's still a few bugs especially around some of the non-default sets but I should be able to nail those down soonish. Overall, I'm pretty happy with where we are now. I'll add a few mentions to use the frontend in the README and call it a day.
